### ISSUE TITLE
[REQUEST]  Output : Writing initial vtk before any computation

### ISSUE THREAD

**Issue by topinvincent** [Collab4exaNBody/exaDEM#141]
When writing outputs reading by paraview (vtk), it seems that, depending on the chosen frequency, the first vtk written is not the initial state.
Is it possible to start computation with first writing the initial state (first vtk)?

**Comment by rprat-pro** [comment]
By default we skip the first step for paraview outputs to avoid conflicts when restarting a simulation with mistakes. 

```
trigger_dump_paraview:
  rebind: { freq: simulation_paraview_frequency , result: trigger_dump_paraview }
  body:
    - nth_timestep: { first: false }
```

To force the paraview outputs at the first timestep, please add these lines to your `input_file.msp` :
```
trigger_dump_paraview:
  rebind: { freq: simulation_paraview_frequency , result: trigger_dump_paraview }
  body:
    - nth_timestep: { first: true }
```
